# Run this to create: conda env create --force -f environment_deploy.yml
name: cointick_deploy
dependencies:
    - python=2.7
    - pip:
        - fabric
        - invoke
        - python-digitalocean

