# Run this to create: conda env create --force -f environment_analysis.yml
# Also need to run the below to get pdvega working
# jupyter nbextension enable vega3 --py --sys-prefix
name: btc_analysis
dependencies:
    - python=3.6
    - pandas
    - dask
    - fastparquet
    - jupyter
    - bokeh=0.12.4=py36_0
    - datashader=0.4.0=py36_0
    - holoviews=1.8.3=py36_0
    - scipy
    - matplotlib
    - pip:
        - pandashells
        - fleming
        - pdvega
    - pip:
        - mpld3
        - pandashells
        - seaborn
